export const movie_list = [
  {
    id: 1,
    image: "1.jpg",
    title: "Prison Break",
    description: "Çok güzel bir dizi",
    is_active: true,
    is_new: true,
  },
  {
    id: 2,
    image: "2.jpg",
    title: "La Casa De Papel",
    description: "Efsane bir dizi",
    is_active: true,
    is_new: true,
  },
  {
    id: 3,
    image: "3.jpg",
    title: "Oppenheimer",
    description: "Efsane bir film",
    is_active: true,
    is_new: true,
  },
  {
    id: 4,
    image: "4.jpg",
    title: "Transcendence",
    description: "Güzel bir film",
    is_active: true,
    is_new: true,
  },
  {
    id: 5,
    image: "5.jpg",
    title: "Small Things Like These",
    description: "Anlamlı bir film",
    is_active: true,
    is_new: true,
  },
  {
    id: 6,
    image: "6.jpg",
    title: "In The Heart Of The Sea",
    description: "Çok iyi bir film",
    is_active: true,
    is_new: true,
  },
];
